# Site settings
title: "Service Cat"
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
port: 			  4156

# Build settings
#markdown: kramdown
exclude: ["README.md"]

#source "https://rubygems.org"
#gem "github-pages", group: :jekyll_plugins
